apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.BlogDeployment.name }}
spec:
  replicas: {{ .Values.BlogDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.BlogDeployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.BlogDeployment.app }}
    spec:
      containers:
      - name: backend-container
        image: {{ .Values.BlogDeployment.image.repository }}:{{ .Values.BlogDeployment.image.tag }}
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://alamziyafzd:8I24Qyhwg5X7hv6G@cluster0.ffzdu.mongodb.net/"
        - name: JWT_SECRET
          value: "MySecretBlog"
